### ISSUE TITLE
IBM cloud network assign public subnet to proxmox host for guest public IPs.

### ISSUE THREAD

**Issue by maboali** [IBM-Bluemix-Docs/subnets#2]
I couldn't find it anywhere so I would like to add it to the documentation but don't know where!
To configure the networks for a new Proxmox (Debain 8) you need to 

1- buy a subnet and make its target the ip of the proxmox host
2- configure the Proxmox host networking
- enable traffic forwarding 
- reboot
- create a bridge vmbr0 and assign the bond1 (eth1, eth 3) and ip dress of bond1 (carrying the host public ip).
- Reboot
- Add the new subnet routing to the host routing
3- create a guest container and assign an IP address

**Proxmox Host Configuration Details**
- enable traffic forwarding 
Run command 
root@px1:~#nano /etc/sysctl.conf

Now make the following changes
Uncomment
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1

- Then reboot
- create a bridge vmbr0 and assign the bond1 (eth1, eth 3) and ip dress of bond1 (carrying the host public ip).

Run command 
root@px1:~#nano  /etc/network/interfaces

Now make the following changes
```
auto bond1
iface bond1 inet static                 # change static to manual
        bond-slaves eth1 eth3
        bond-miimon 100
        bond-mode 802.3ad
        bond-lacp-rate fast
        bond-downdelay 0
        bond-updelay 0
        bond-xmit_hash_policy 1 
        address  x.x.x.x.x                 # Comment this line
        netmask  xx                          # Comment this line
        Gateway. x.x.x.y                   # Comment this line

auto vmbr0
iface vmbr0 inet manual                       # convert manual to static      
        address  x.x.x.x                              # copy this line from the bond1 to here
        netmask  xx                                    # copy this line from the bond1 to here
        gateway  x.x.x.y                             # copy this line from the bond1 to here
        bridge-ports none                        # replace none with bond1                       
        bridge-stp off
        bridge-fd 0


```
- Reboot
- Add the new subnet routing to the host routing
      
```
up ip route add 192.168.0.0/24 dev vmbr0             # route for the whole subnet
up ip route add 192.168.0.1/32 dev vmbr0        # route for each IP address  note: the mask is /32
up ip route add 192.168.0.2/32 dev vmbr0       # note use the the public its instead.
up ip route add 192.168.0.3/32 dev vmbr0
up ip route add 192.168.0.4/32 dev vmbr0

```

Continue till the last IP address in the subnet

- Reboot

Now assign any ip to a vm and try pining it from any public.

**Comment by austinmama** [comment]
Sent inquiry to development.
