### ISSUE TITLE
Static to VLAN-routed

### ISSUE THREAD

**Issue by bkoohi** [IBM-Bluemix-Docs/subnets#3]
Hi There - IBM Cloud has depreciated a type of subnet that was very useful for some use cases such as routing a bare-metal traffic to a VMware NSX env. Since unfortunately this feature has been removed, there is a need to offer an alternative and in my discussion with some of sdn folks, they recommended an alternative. Could you please add this work around content to this page:

Depreciated feature:
https://cloud.ibm.com/docs/subnets?topic=subnets-deprecating-static-to-vlan-routed-subnets

Workaround:
Behzad Koohi  1 day ago
without a perimeter FW like juniper…and customer using VPN in their NSX to connect to on-prem, what do you recommend for routing external bare-metal traffic in cloud to NSX layer?

JACK CHERKAS:happyminion:  1 day ago
Either NAT on NSX ESG or using portable private IP added on both Bare Metal and on vNIC of ESG in same subnet, then static routes on Bare Metal, using new vNIC on NSX ESG as gateway for specific subnets (edited) 

Behzad Koohi  1 day ago
for portable private subnet in both bare-metal and vNIC on ESG option

Behzad Koohi  1 day ago
I can change the default gateway on on BM to point to vNIC on ESG

JACK CHERKAS:happyminion:  1 day ago
Or add static route for specific subnets you want to be able to route to

Behzad Koohi  1 day ago
right

JACK CHERKAS:happyminion:  1 day ago
If you change default gateway, make sure you add static routes for IBM Cloud Subnets (including Services and SSL VPN, etc…) to BCR

Behzad Koohi  1 day ago
correct. good point.

Behzad Koohi  1 day ago
To get to on-prem , I still have to NAT.

Behzad Koohi  1 day ago
customer wants to use their VXLAN IPs ( 10.17 ) to get to BM

Behzad Koohi  1 day ago
I see two options you described in above as two parts of one solution

JACK CHERKAS:happyminion:  1 day ago
Depends upon if there is IP conflicts between IBM Cloud underlay and customer network

Behzad Koohi  1 day ago
I think you are thinking of adding portable subnet to the tunnel to access from on-prem, Correct?

JACK CHERKAS:happyminion:  1 day ago
Yes you can do

Behzad Koohi  1 day ago
we do have conflict and they are interested to use their VXLAN ips

JACK CHERKAS:happyminion:  1 day ago
So then yes NAT

Behzad Koohi  1 day ago
Got. It. Thanks Jack. As usual, you are very helpful and stay safe.

Thomas Narten  1 day ago
Routed to VLAN addresses. They were always an oddity. And they’ve been deprecated. And I didn’t even notice. Says something. :slightly_smiling_face: Sounds like Jack has outlined the usual ways to get from overlay (and on prem) to BM when NSX is involved.

**Comment by austinmama** [comment]
Sent note to Jack to assist with doc updates

**Comment by austinmama** [comment]
Jack out until Dec.  Sent to Thomas Narten.

**Comment by austinmama** [comment]
No response.  Consulted Bare Metals writer.   BM VMware flavor already uses NSX ([https://cloud.ibm.com/docs/vmware?topic=vmware-nsx-overview](https://cloud.ibm.com/docs/vmware?topic=vmware-nsx-overview)). Subnets, porting, VPN, etc. are all documented in their own doc collections.  

The following topic points customers to the appropriate documentation.  Other than the deprecation note, no further doc action is required.

[https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-network-options](https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-network-options) 

Any affected customers were notified about the depreciation along with a transition plan.
