### ISSUE TITLE
the subnets help  https://cloud.ibm.com/docs/subnets?topic=subnets-gettinghelp-subnets requires some updates

### ISSUE THREAD

**Issue by dotch3** [IBM-Bluemix-Docs/subnets#5]
the idea to have the "status" page is not need there.
`Check the status of the IBM Cloud platform and resources by going to the [Status page](https://cloud.ibm.com/status).`

The second paragraph on "Providing support case details for subnets" is just a bad copy/paste, the paragraph mentions " vlans" . it should not be there

`To ensure that the support team has all of the details for investigating your issue to provide a timely resolution, you must provide detailed information about your issue. Review the following tips about the type of information to include in your support case for issues with vlans.`

**Comment by Lauren-Fulcher** [comment]
Thank you for your feedback @dotch3, I've made the updates you suggested.
